# Generated by Django 6.0.5 on 2026-05-29 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_blog_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='readmore',
            name='addtofav',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fav_blog', to='blogapp.blog'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='readmore',
            name='readmore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_blog', to='blogapp.blog'),
        ),
        migrations.AlterField(
            model_name='readmore',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
