# Generated by Django 6.0.5 on 2026-05-29 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_readmore_addtofav_alter_readmore_readmore_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readmore',
            name='addtofav',
        ),
    ]
